// <auto-generated />
using FlightApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightApp.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("FlightApp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightApp.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalCity = "LEJ",
                            Capacity = 133,
                            DepartureCity = "ORY",
                            DepartureDate = "2023-04-13",
                            Price = 1289.0,
                            ReturnDate = "2023-04-17"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalCity = "ORY",
                            Capacity = 140,
                            DepartureCity = "LEJ",
                            DepartureDate = "2023-04-13",
                            Price = 203.0,
                            ReturnDate = "2023-04-14"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalCity = "LEJ",
                            Capacity = 133,
                            DepartureCity = "ORY",
                            DepartureDate = "2023-04-15",
                            Price = 911.0,
                            ReturnDate = "2023-04-17"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalCity = "LEJ",
                            Capacity = 76,
                            DepartureCity = "ORY",
                            DepartureDate = "2023-04-13",
                            Price = 1206.0,
                            ReturnDate = "2023-04-17"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalCity = "LEJ",
                            Capacity = 13,
                            DepartureCity = "FEZ",
                            DepartureDate = "2023-04-13",
                            Price = 314.0,
                            ReturnDate = "2023-04-18"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
