version: '3.9'

services:
  frontend:
    build: ./flightapp
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./FlightAppBackend/FlightApp/FlightApp
    ports:
      - '80:80'
      - '443:443'
      - '44316:44316'
